version: "3.8"

services:
  postgres:
    image: postgres:16
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres

  server:
    build: .
    ports:
      - 4000:4000
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres
      - BASE_URL=http://localhost:4000
      - SECRET=test

    depends_on:
      - postgres
